# Generated by Django 3.2.6 on 2021-11-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Stream', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='group',
        ),
    ]
