# Generated by Django 3.2.6 on 2021-11-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Stream', '0003_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=264),
        ),
    ]
